### ISSUE TITLE
Timeline not showing up

### ISSUE THREAD

**Issue by christianhau** [aysark/dashing-timeline#11]
Hi!

I have followed the instructions and added the files in the locations specified. After adding 

```
<li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
  <div data-id="a_timeline" data-view="Timeline" data-title="Timeline"></div>
</li>
```
to the dashboard .erb file as well as adding moment.min.js to the layout.erb file like this there is simply nothing showing in the dashboard.
```
<!-- The javascript and css are managed by sprockets. The files can be found in the /assets folder-->
  <script type="text/javascript" src="/assets/application.js"></script>
  <script type="text/javascript" src="/assets/moment.min.js"></script>
  <link rel="stylesheet" href="/assets/application.css">
```

As i can't see anything in the dashboard and there are no error messages when I start up smashing I am struggling to see what I am doing wrong, any help would be appreciated!

**Comment by aysark** [comment]
This plugin as the name states is for dashing.io not smashing.  I did not do a port over to smashing, so i'd imagine there are changes needed to make it work for smashing, sorry.
