### ISSUE TITLE
timeline.coffee has dimensions hardcoded, shouldn't it be reactive to size of grids?

### ISSUE THREAD

**Issue by painbank** [aysark/dashing-timeline#3]
as the title states, it seems the size is hardcoded in the timeline.coffee, so it fixes it at that size and when a grid layout is setup that is different, then the widget doesn't fit the new layout.

**Comment by painbank** [comment]
An additional problem or constraint of using this widget is the height is dynamic based on the events in the timeline_data.yml.

**Comment by aysark** [comment]
Yes, i agree that was somewhat hacky on my part.  Welp, this is open for a PR.
