### ISSUE TITLE
mac os X has timeline not being found

### ISSUE THREAD

**Issue by painbank** [aysark/dashing-timeline#4]
I can find the file on a Mac OS X Yosemite if I put timeline_data.yml in the jobs directory and change this line as follows in timeline.rb job.

```
#config_file = File.dirname(File.expand_path(__FILE__)) + '../timeline_data.yml'
config_file = File.dirname(File.expand_path(__FILE__)) + '/timeline_data.yml'
```

**Comment by aysark** [comment]
Can't test on mac atm, but try fiddling with the string, maybe remove the / prefix.

The File methods should be OS independent.
