### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sipandey** [aysark/dashing-timeline#9]
Hi,
In the timeknots.js file 
it is looking for var timestamps = events.map(function(d)
but seems like events is not defined.

I have tried everything but nothing works.

If you can provide some insight as to what I am missing.

Thanks,
Sid

**Comment by estel1212** [comment]
Hi,
I try it today also the feature. I get the same error as described by sipandey...
Can you please provide some help for this problem.

Thanks,
Radouane

**Comment by aysark** [comment]
This is a plugin to the [Dashing.io](Dashing.io) it assumes you have that setup.  Dashing will provide the events param to this plugin.
